"""V11_ALT_heuristics — V11-vs-V10.6.2 comparison + honest verdict report.

Reads V11 forensic/changepoint/compound outputs and the frozen V10.6.2
earliest_signal_per_vin.csv, then emits:
  results/V11_ALT_heuristics_comparison.csv  (per-failed-VIN head-to-head)
  reports/V11_ALT_heuristics_report.md       (summary + per-feature classification)
"""
from __future__ import annotations

import importlib.util
import pathlib

import numpy as np
import pandas as pd

_src = pathlib.Path(__file__).resolve().parent


def _load(name):
    spec = importlib.util.spec_from_file_location(name, str(_src / f"{name}.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


cfg = _load("V11_ALT_heuristics_config")
FORENSICS = cfg.FORENSICS


def classify_feature(failed_hits: int, nf_false: int) -> str:
    if nf_false >= 2:
        return "false_alarm_prone"
    if failed_hits >= 2:
        return "generalizes"
    if failed_hits == 1:
        return "anecdotal"
    return "no_signal"


def _hzn(v):
    try:
        return int(v)
    except (TypeError, ValueError):
        return -1


def main() -> None:
    cfg.RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    cfg.REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    v11 = pd.read_csv(FORENSICS / "earliest_signal_per_vin.csv")
    v1062 = pd.read_csv(cfg.V1062_FORENSICS / "earliest_signal_per_vin.csv")
    dev = pd.read_csv(FORENSICS / "failed_window_deviations.csv")
    self_test = pd.read_csv(FORENSICS / "nf_self_test.csv")
    cp = pd.read_csv(FORENSICS / "changepoint_per_vin.csv")
    comp = pd.read_csv(FORENSICS / "compound_alarm_lovo.csv")

    a = v1062.set_index("vin_label")
    b = v11.set_index("vin_label")
    rows = []
    for vin in cfg.FAILED_VIN_SET:
        ra = a.loc[vin] if vin in a.index else None
        rb = b.loc[vin] if vin in b.index else None
        rows.append({
            "vin_label": vin,
            "v1062_horizon": ra["earliest_discriminative_horizon_days"] if ra is not None else "none",
            "v1062_feature": ra["feature"] if ra is not None else "",
            "v11_horizon": rb["earliest_discriminative_horizon_days"] if rb is not None else "none",
            "v11_feature": rb["feature"] if rb is not None else "",
            "earlier": _hzn(rb["earliest_discriminative_horizon_days"]) > _hzn(ra["earliest_discriminative_horizon_days"])
                       if (ra is not None and rb is not None) else False,
            "new_in_v11": (ra is None or str(ra["earliest_discriminative_horizon_days"]) == "none")
                          and (rb is not None and str(rb["earliest_discriminative_horizon_days"]) != "none"),
        })
    comparison = pd.DataFrame(rows)
    comparison.to_csv(cfg.RESULTS_DIR / "V11_ALT_heuristics_comparison.csv", index=False)

    disc = dev[dev["discriminative"] == True]               # noqa: E712
    feat_rows = []
    nf_false_by_feat = self_test[self_test["verdict"] == "FALSE_ALARM"]["feature"].value_counts()
    for f in cfg.NEW_FEATS:
        failed_hits = disc[disc["feature"] == f]["vin_label"].nunique()
        nf_false = int(nf_false_by_feat.get(f, 0))
        feat_rows.append({"feature": f, "failed_vins_discriminative": failed_hits,
                          "nf_false_alarms": nf_false,
                          "class": classify_feature(failed_hits, nf_false)})
    feat_df = pd.DataFrame(feat_rows).sort_values(
        ["class", "failed_vins_discriminative"], ascending=[True, False])

    n11 = int((v11["verdict"] == "discriminative_precursor").sum())
    n1062 = int((v1062["verdict"] == "discriminative_precursor").sum())
    n_false = int((self_test["verdict"] == "FALSE_ALARM").sum())
    fired_f = int(comp[(comp.group == "FAILED") & (comp.fired == True)].shape[0])   # noqa: E712
    fired_nf = int(comp[(comp.group == "NF") & (comp.fired == True)].shape[0])      # noqa: E712

    md = []
    md.append("# V11_ALT_heuristics — Lead-Time Heuristics vs V10.6.2\n")
    md.append(f"_Generated by V11_ALT_heuristics_compare. Honest gate: within-truck "
              f"z>=2 AND outside NF p05-p95, MIN_EO_SAMPLES={cfg.MIN_EO_SAMPLES}._\n")
    md.append("## Headline\n")
    md.append(f"- **Discriminative-precursor recall:** V11 **{n11}/10** vs V10.6.2 {n1062}/10\n")
    md.append(f"- **NF self-test false alarms (15 NF as-if-failing):** {n_false}/15\n")
    md.append(f"- **Compound early-watch (#11):** recall {fired_f}/10 failed, "
              f"{fired_nf}/15 NF false alarms\n")
    md.append("\n## Per-failed-VIN head-to-head\n")
    md.append(comparison.to_markdown(index=False))
    md.append("\n\n## New-feature generalization (which of the 12 helped)\n")
    md.append(feat_df.to_markdown(index=False))
    md.append("\n\n## Change-point / dose-knee / resting-slope lead times (#12/#5/#6)\n")
    md.append(cp.to_markdown(index=False))
    md.append("\n\n## Honest verdict\n")
    if n11 > n1062:
        md.append(f"- V11 raises discriminative recall by {n11 - n1062} VIN(s) over V10.6.2.\n")
    else:
        md.append("- V11 does NOT raise discriminative recall above V10.6.2; new features add "
                  "fault-mode coverage / lead but not new detections.\n")
    gen = feat_df[feat_df["class"] == "generalizes"]["feature"].tolist()
    anec = feat_df[feat_df["class"] == "anecdotal"]["feature"].tolist()
    fap = feat_df[feat_df["class"] == "false_alarm_prone"]["feature"].tolist()
    md.append(f"- Generalizing new features (>=2 failed, 0-1 NF false): {gen or 'none'}\n")
    md.append(f"- Anecdotal (single-VIN) features: {anec or 'none'}\n")
    md.append(f"- False-alarm-prone features (>=2 NF false): {fap or 'none'}\n")
    md.append("- Structural limit (V10.6.2 sec 5) unchanged: no per-truck daily RUL; "
              "deliverable stays WHICH (classifier) + WHEN-fleet (Weibull) + WHEN-emergency.\n")

    out = cfg.REPORTS_DIR / "V11_ALT_heuristics_report.md"
    out.write_text("\n".join(md), encoding="utf-8")
    print(f"[v11 compare] wrote {out}")
    print(f"  recall V11 {n11}/10 vs V10.6.2 {n1062}/10; NF false {n_false}/15")


if __name__ == "__main__":
    main()
